apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-demo
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-demo
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0
